language: c

addons:
  apt:
    packages:
      - cmake
      - gcovr

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

jobs:
  include:
    - stage: test
      script: ./rta_test

    - stage: code coverage
      script: gcovr -r .. -e ../gtest/
      #  - mkdir coverage_results 
      #  - gcovr -r .. -e ../gtest/ --html --html-details -o coverage_results/coverage.html

# Не показывает coverage_results и почему-то выкладывает весь проект
#
# deploy:
#   provider: releases
#   api_key: '$GITHUB_API_KEY'
#   file_glob: true
#   file: build/coverage_results/*
#   skip_cleanup: true
#   on:
#     tags: true