language: c

addons:
  apt:
    packages:
    - cmake

before_install:
  - sudo apt-get -y install libgtest-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

jobs:
  include:
    - stage: test
      script: ./rta_test