language: c

addons:
  apt:
    packages:
      - cmake
      - cppcheck
      - valgrind

before_install:
  - pip install gcovr
  - pip install cpplint

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..

jobs:
  include:
    - stage: running tests
      script:
        - ./build/rta_test 

    - stage: valgrind
      script:
        - valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./build/rta_test 

    - stage: checking code coverage
      script:
        - ./build/rta_test
        - mkdir coverage_results 
        - python -m gcovr -r . -e gtest/ -e *.cpp --xml-pretty -o coverage_results/coverage.xml
        - ./codecov -f coverage_results/coverage.xml

    - stage: cpplint
      script: python -m cpplint *.c

    - stage: cppcheck
      script: cppcheck --error-exitcode=1 *.c
