language: c

addons:
  apt:
    packages:
      - cmake

before_install:
  - python3 -m pip install --upgrade pip
  - pip install gcovr
  - pip install cpplint

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

jobs:
  include:
    - stage: running tests
      script: ./rta_test

    - stage: checking code coverage
      script:
        - ./rta_test
        - gcovr -r .. -e ../gtest/
      #  - mkdir coverage_results 
      #  - gcovr -r .. -e ../gtest/ --html --html-details -o coverage_results/coverage.html

    - stage: cpplint
      script:
        - cpplint ../*.c

# Не показывает coverage_results и почему-то выкладывает весь проект
#
# deploy:
#   provider: releases
#   api_key: '$GITHUB_API_KEY'
#   file_glob: true
#   file: build/coverage_results/*
#   skip_cleanup: true
#   on:
#     tags: true