dist: trusty
language: c

addons:
  apt:
    packages:
      - cmake
      - cppcheck
      - valgrind
      - python3
      - python3-pip

before_install:
  - pip3 install gcovr
  - pip3 install cpplint

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..

jobs:
  include:
    - stage: running tests
      script:
        - ./build/rta_test 

    - stage: valgrind
      script:
        - valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./build/rta_test 

    - stage: checking code coverage
      script:
        - ./build/rta_test
        - mkdir coverage_results 
        - python3 -m gcovr -r . -e gtest/ --txt -o coverage_results/coverage.txt
        - ./codecov -f coverage_results/coverage.txt

    - stage: cpplint
      script: cpplint *.c

    - stage: cppcheck
      script: python3 -m cppcheck --error-exitcode=1 *.c
